//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2021
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FoundStranger
    {
        public int FoundStrangerID { get; set; }

        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        [Display(Name = "Фамилия")]
        [MaxLength(30, ErrorMessage = "Вы превысили возможное количество символов")]
        public string Surname { get; set; }

        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        [Display(Name = "Имя")]
        [MaxLength(30, ErrorMessage = "Вы превысили возможное количество символов")]
        public string Name { get; set; }

        [Display(Name = "Отчество")]
        [MaxLength(30, ErrorMessage = "Вы превысили возможное количество символов")]
        public string Patronymic { get; set; }

        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        public int Gender { get; set; }

        [MaxLength(200, ErrorMessage = "Вы превысили возможное количество символов")]
        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        public string CurrentLocation { get; set; }

        [MaxLength(60, ErrorMessage = "Вы превысили возможное количество символов")]
        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        public string FullAplicant { get; set; }

        [Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        [RegularExpression(@"^((\+7|7|8)+([0-9]){10})$", ErrorMessage = "Неправильный номер телефона")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }

        //[Required(ErrorMessage = "Это поле обязательно для заполнения!")]
        public byte[] Image { get; set; }

        public virtual Gender Gender1 { get; set; }
    }
}
