//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2021
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventContext : DbContext
    {
        public EventContext()
            : base("name=CourceWork1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<FoundStranger> FoundStrangers { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<MissingPerson> MissingPersons { get; set; }
        public virtual DbSet<SearchCampaign> SearchCampaigns { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<StaffVolunteer> StaffVolunteers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
